version: '3.9'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "3036:3036"
    command: bash -c "bundle install && ./bin/dev"
        # command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - mailcatcher
      - redis
    environment:
      - TZ=Asia/Tokyo
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
