version: '3.9'

volumes:
  puma-sock:

services:
  app:
    build: .
    volumes:
      - .:/app
      - puma-sock:/app/tmp/sockets
    ports:
      - "3000:3000"
      - "3036:3036"
    # command: bash -c "bundle install && ./bin/dev"
    command: bundle exec puma -e development
    depends_on:
      - mailcatcher
      - redis
    environment:
      - TZ=Asia/Tokyo

  web:
    build:
      context: ./docker
      dockerfile: nginx/Dockerfile
    volumes:
      - puma-sock:/var/www/tmp/sockets
    ports:
      - "${WEB_PORT}:80"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
